// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMSG4si9d0h607dqsszMi1mSSzoU6PB2s',
    appId: '1:736983815184:web:52cab25a60a1f0bf416695',
    messagingSenderId: '736983815184',
    projectId: 'petbite-d975e',
    authDomain: 'petbite-d975e.firebaseapp.com',
    storageBucket: 'petbite-d975e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCySroX5v6wnVVCLxXLQM_taTHqvofxnsU',
    appId: '1:736983815184:android:3d4d00d54c40edbf416695',
    messagingSenderId: '736983815184',
    projectId: 'petbite-d975e',
    storageBucket: 'petbite-d975e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdb0FBE6rWsou-nSIXJNFvRGGPgr1l_jU',
    appId: '1:736983815184:ios:9ac00f22f6e59484416695',
    messagingSenderId: '736983815184',
    projectId: 'petbite-d975e',
    storageBucket: 'petbite-d975e.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdb0FBE6rWsou-nSIXJNFvRGGPgr1l_jU',
    appId: '1:736983815184:ios:303dce281b9630e1416695',
    messagingSenderId: '736983815184',
    projectId: 'petbite-d975e',
    storageBucket: 'petbite-d975e.appspot.com',
    iosBundleId: 'com.example.app.RunnerTests',
  );
}
